# Generated by Django 5.1.6 on 2025-10-22 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('Book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=69)),
                ('Book_price', models.FloatField()),
                ('Book_publication', models.CharField(max_length=69)),
                ('Book_publish_year', models.DateField(default=datetime.date(2025, 10, 22))),
                ('Book_quantity', models.CharField(max_length=69)),
                ('Book_stack', models.BooleanField(default=True)),
            ],
        ),
    ]
