# Generated by Django 5.1.6 on 2025-10-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='Book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='Book_publish_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
