# Generated by Django 5.1.6 on 2025-10-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_info_book_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_info',
            old_name='Book_publication',
            new_name='Book_Author',
        ),
    ]
