# Generated by Django 5.1.6 on 2025-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_rename_book_publication_book_info_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='Book_quantity',
            field=models.IntegerField(max_length=69),
        ),
    ]
