# Generated by Django 5.1.6 on 2025-11-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_info_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='Book_quantity',
            field=models.IntegerField(),
        ),
    ]
